export { authService } from './auth.service';
export { usersService, employeesService } from './users.service';
export { projectsService } from './projects.service';
export { tasksService } from './tasks.service';
export { eventsService } from './events.service';
export { vacationsService } from './vacations.service';
export { analyticsService } from './analytics.service';
export { notificationsService } from './notifications.service';
export { messengerService } from './messenger.service';
export { integrationsService } from './integrations.service';
export type { TelegramContact, WhatsAppContact, IntegrationMessage } from './integrations.service';
